# This file is a template, and might need editing before it works on your project.
# Official docker image.

stages:
  - test
  - build
  - deploy

image: docker:latest

services:
  - name: docker:dind
    command: ["--insecure-registry=registry.alireza.com"]

before_script:
  - echo "192.168.0.122 registry.alireza.com" >> /etc/hosts
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" http://registry.alireza.com:5000

sample-production-build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

sample-production-deploy:
  stage: deploy
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master
